---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lemg1635/presensi/
    - export PUBLICPATH=/home/lemg1635/public_html/presensi.lemdiklattarunanusantaraindonesia.id/

    # 1. Update Core Laravel (di luar public_html agar aman)
    - /bin/cp -R backend/* $DEPLOYPATH
    - /bin/cp -R backend/.* $DEPLOYPATH

    # 2. Update Public Files (Tanpa mengganggu folder storage symlink)
    - /usr/bin/rsync -av --exclude='storage' backend/public/ $PUBLICPATH
    
    # 3. Jalankan Artisan Command
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan down
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan up

