---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lemg1635/presensi/
    - export PUBLICPATH=/home/lemg1635/public_html/presensi/

    # 1. Update Core Laravel (di luar public_html agar aman)
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .* $DEPLOYPATH

    # 2. Update Public Files (Tanpa mengganggu folder storage symlink)
    - /usr/bin/rsync -av --exclude='storage' public/ $PUBLICPATH

        # Hapus file usang yang tersangkut (ghost files)
    - /bin/rm -f $DEPLOYPATH/database/migrations/0000_00_00_000000_create_companies_table.php
    - /bin/rm -f $DEPLOYPATH/database/migrations/2026_08_07_031147_add_geofence_to_companies_table.php
    - /bin/rm -rf $DEPLOYPATH/app/Filament/Resources/Companies
    
    # 3. Jalankan Artisan Command
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan down
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan up

