import React, { useEffect, useState } from 'react';
import { FileUp, Loader2, Megaphone, Pencil, Trash2 } from 'lucide-react';
import api from '../../api';

export default function AdminAnnouncements() {
    const [form, setForm] = useState({ title: '', content: '', priority: 'normal', target_type: 'company', target_value: '' });
    const [attachment, setAttachment] = useState(null);
    const [saving, setSaving] = useState(false);
    const [message, setMessage] = useState('');
    const [items, setItems] = useState([]);
    const [editing, setEditing] = useState(null);
    const load = async () => { const response = await api.get('/admin/announcements'); setItems(response.data?.data || []); };
    useEffect(() => { load().catch(() => setMessage('Daftar pengumuman gagal dimuat.')); }, []);
    const submit = async (event) => {
        event.preventDefault(); setSaving(true); setMessage('');
        const payload = new FormData(); Object.entries(form).forEach(([key,value]) => value && payload.append(key,value)); if (attachment) payload.append('attachment', attachment);
        try { if (editing) { payload.append('_method','PUT'); await api.post(`/admin/announcements/${editing.id}`, payload, { headers: {'Content-Type':'multipart/form-data'} }); } else { await api.post('/admin/announcements', payload, { headers: {'Content-Type':'multipart/form-data'} }); } setForm({ title:'', content:'', priority:'normal', target_type:'company', target_value:'' }); setAttachment(null); setEditing(null); setMessage('Pengumuman berhasil disimpan.'); await load(); }
        catch (error) { setMessage(error.response?.data?.message || 'Pengumuman gagal dipublikasikan.'); } finally { setSaving(false); }
    };
    const edit = item => { setEditing(item); setForm({title:item.title,content:item.body||'',priority:item.priority||'normal',target_type:item.target_type||'company',target_value:item.target_value||''}); window.scrollTo({top:0,behavior:'smooth'}); };
    const remove = async item => { if(!window.confirm(`Hapus “${item.title}”?`)) return; await api.delete(`/admin/announcements/${item.id}`); await load(); };
    return <div className="mx-auto max-w-4xl space-y-6 p-6 md:p-8"><div className="flex items-center gap-3"><span className="rounded-2xl bg-amber-100 p-3 text-amber-700"><Megaphone/></span><div><h1 className="text-3xl font-bold text-slate-900">Kelola Pengumuman</h1><p className="text-slate-500">Pengumuman ini tampil pada website dan mobile karyawan.</p></div></div><form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><input required placeholder="Judul pengumuman" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="w-full rounded-xl border border-slate-200 px-4 py-3"/><textarea required rows="7" placeholder="Isi pengumuman" value={form.content} onChange={e=>setForm({...form,content:e.target.value})} className="w-full rounded-xl border border-slate-200 px-4 py-3"/><div className="grid gap-4 md:grid-cols-2"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="rounded-xl border border-slate-200 px-4 py-3"><option value="normal">Normal</option><option value="high">Tinggi</option><option value="urgent">Penting</option><option value="low">Rendah</option></select><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 px-4 py-3 text-sm text-slate-600"><FileUp className="h-5 w-5"/>{attachment?.name || 'Pilih gambar/PDF (opsional)'}<input type="file" accept=".jpg,.jpeg,.png,.pdf" onChange={e=>setAttachment(e.target.files?.[0]||null)} className="hidden"/></label></div>{message && <p className="text-sm text-emerald-700">{message}</p>}<button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-semibold text-white">{saving && <Loader2 className="h-4 w-4 animate-spin"/>}{editing?'Simpan perubahan':'Publikasikan'}</button></form><div className="space-y-3">{items.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-4"><div><h2 className="font-bold text-slate-900">{item.title}</h2><p className="mt-2 text-sm text-slate-600">{item.body}</p><span className="mt-3 block text-xs uppercase text-slate-400">{item.priority} • {item.target_type}</span></div><div className="flex gap-2"><button onClick={()=>edit(item)} className="rounded-lg bg-blue-50 p-2 text-blue-700"><Pencil className="h-4 w-4"/></button><button onClick={()=>remove(item)} className="rounded-lg bg-rose-50 p-2 text-rose-700"><Trash2 className="h-4 w-4"/></button></div></div></article>)}</div></div>;
}
