<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AttendanceLog;
use App\Models\EmployeeBiometric;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class AttendanceController extends Controller
{
    /**
     * Store the face embedding generated by the mobile app during enrollment.
     */
    public function enrollFace(Request $request)
    {
        $user = $request->user();
        if (!$user->employee) {
            return response()->json(['message' => 'Employee profile not found.'], 403);
        }

        $validator = Validator::make($request->all(), [
            'face_embedding' => 'required|array',
            'device_id' => 'required|string',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $biometric = EmployeeBiometric::updateOrCreate(
            ['employee_id' => $user->employee->id, 'company_id' => $user->company_id],
            [
                'face_embedding' => $request->face_embedding,
                'enrolled_at' => now(),
                'device_id' => $request->device_id,
            ]
        );

        // Update the employee flag for convenience
        $user->employee->update([
            'face_enrolled' => true,
            'face_enrolled_at' => now(),
        ]);

        return response()->json(['message' => 'Face enrollment successful.']);
    }

    /**
     * Calculate distance between two coordinates in meters (Haversine formula).
     */
    private function calculateDistanceMeters($lat1, $lon1, $lat2, $lon2)
    {
        $earthRadius = 6371000; // meters

        $dLat = deg2rad($lat2 - $lat1);
        $dLon = deg2rad($lon2 - $lon1);

        $a = sin($dLat / 2) * sin($dLat / 2) +
             cos(deg2rad($lat1)) * cos(deg2rad($lat2)) *
             sin($dLon / 2) * sin($dLon / 2);

        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));

        return $earthRadius * $c;
    }

    /**
     * Check-in an employee.
     */
    public function checkIn(Request $request)
    {
        $user = $request->user();
        $employee = $user->employee;
        $company = $user->company;

        if (!$employee) {
            return response()->json(['message' => 'Employee profile not found.'], 403);
        }

        $validator = Validator::make($request->all(), [
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
            'face_match_score' => 'required|numeric',
            'device_id' => 'required|string',
            'flags' => 'nullable|array',
            'photo' => 'nullable|image|max:10240', // 10MB max
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $status = 'present';
        $flags = $request->flags ?? [];

        // Geofence Check
        if ($company->latitude && $company->longitude) {
            $distance = $this->calculateDistanceMeters(
                $request->latitude,
                $request->longitude,
                $company->latitude,
                $company->longitude
            );

            if ($distance > ($company->geofence_radius_meters ?? 50)) {
                $status = 'flagged';
                $flags['outside_geofence'] = true;
                $flags['distance_meters'] = round($distance);
            }
        }

        // Spoofing Checks
        if (isset($flags['is_mock_location']) && $flags['is_mock_location'] == true) {
            $status = 'flagged';
        }

        if ($request->face_match_score < 0.8) { // Arbitrary threshold
            $status = 'flagged';
            $flags['low_face_match_score'] = true;
        }

        // Make sure not already checked in today
        $existingLog = AttendanceLog::where('employee_id', $employee->id)
            ->whereDate('check_in_at', Carbon::today())
            ->first();

        if ($existingLog) {
            return response()->json(['message' => 'Already checked in today.'], 422);
        }

        $photoPath = null;
        if ($request->hasFile('photo')) {
            $photoPath = $request->file('photo')->store('attendance', 'public');
        }

        $attendance = AttendanceLog::create([
            'employee_id' => $employee->id,
            'company_id' => $company->id,
            'check_in_at' => now(),
            'check_in_latitude' => $request->latitude,
            'check_in_longitude' => $request->longitude,
            'check_in_face_score' => $request->face_match_score,
            'device_id' => $request->device_id,
            'check_in_photo_url' => $photoPath,
            'photo_path' => $photoPath,
            'flags' => $flags,
            'status' => $status,
        ]);

        // Trigger notification if flagged (simulated)
        if ($status === 'flagged') {
            app(\App\Services\NotificationService::class)->sendToHr(
                $company->id,
                'Suspicious Check-in Flagged',
                "{$employee->full_name} had a suspicious check-in."
            );
        }

        return response()->json(['message' => 'Check-in successful', 'data' => $attendance]);
    }

    /**
     * Check-out an employee.
     */
    public function checkOut(Request $request)
    {
        $user = $request->user();
        $employee = $user->employee;
        
        $validator = Validator::make($request->all(), [
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $attendance = AttendanceLog::where('employee_id', $employee->id)
            ->whereDate('check_in_at', Carbon::today())
            ->first();

        if (!$attendance) {
            return response()->json(['message' => 'No active check-in found for today.'], 404);
        }

        if ($attendance->check_out_at) {
            return response()->json(['message' => 'Already checked out today.'], 422);
        }

        $attendance->update([
            'check_out_at' => now(),
            'check_out_gps' => [
                'latitude' => $request->latitude,
                'longitude' => $request->longitude,
            ],
        ]);

        return response()->json(['message' => 'Check-out successful', 'data' => $attendance]);
    }

    /**
     * Retrieve attendance history.
     */
    public function history(Request $request)
    {
        $user = $request->user();
        
        $history = AttendanceLog::where('employee_id', $user->employee->id)
            ->orderBy('check_in_at', 'desc')
            ->paginate(15);
            
        return response()->json($history);
    }
}
