<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AttendanceLog;
use App\Models\EmployeeBiometric;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use App\Services\FaceDescriptorService;
use App\Services\ShiftTimeService;

class AttendanceController extends Controller
{
    /**
     * Store the face embedding generated by the mobile app during enrollment.
     */
    public function enrollFace(Request $request)
    {
        $user = $request->user();
        if (!$user->employee) {
            return response()->json(['message' => 'Employee profile not found.'], 403);
        }

        $validator = Validator::make($request->all(), [
            'face_embedding' => 'required|array',
            'device_id' => 'required|string',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $biometric = EmployeeBiometric::updateOrCreate(
            ['employee_id' => $user->employee->id, ],
            [
                'face_embedding' => $request->face_embedding,
                'enrolled_at' => now(),
                'device_id' => $request->device_id,
            ]
        );

        // Update the employee flag for convenience
        $user->employee->update([
            'face_enrolled' => true,
            'face_enrolled_at' => now(),
        ]);

        return response()->json(['message' => 'Face enrollment successful.']);
    }

    /**
     * Calculate distance between two coordinates in meters (Haversine formula).
     */
    private function calculateDistanceMeters($lat1, $lon1, $lat2, $lon2)
    {
        $earthRadius = 6371000; // meters

        $dLat = deg2rad($lat2 - $lat1);
        $dLon = deg2rad($lon2 - $lon1);

        $a = sin($dLat / 2) * sin($dLat / 2) +
             cos(deg2rad($lat1)) * cos(deg2rad($lat2)) *
             sin($dLon / 2) * sin($dLon / 2);

        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));

        return $earthRadius * $c;
    }

    /**
     * Check-in an employee.
     */
    public function checkIn(Request $request)
    {
        $user = $request->user();
        $employee = $user->employee;
        $shiftClock = app(ShiftTimeService::class);
        $businessNow = $shiftClock->now();
        [$dayStartUtc, $dayEndUtc] = $shiftClock->utcDayBounds($businessNow);

        if (!$employee) {
            return response()->json(['message' => 'Employee profile not found.'], 403);
        }

        $flags = $request->flags;
        if (is_string($flags)) {
            $flags = json_decode($flags, true);
            $request->merge(['flags' => $flags]);
        }

        $validator = Validator::make($request->all(), [
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
            'face_match_score' => 'required|numeric',
            'face_descriptor' => 'nullable|array|size:128',
            'face_descriptor.*' => 'numeric|between:-10,10',
            'device_id' => 'required|string',
            'address' => 'nullable|string',
            'flags' => 'nullable|array',
            'photo' => 'nullable|image|max:10240',
            'shift_assignment_id' => 'nullable|integer',
            'shift_template_id' => 'nullable|integer',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $status = 'present';
        $flags = $request->flags ?? [];

        // Geofence Check
        $geofenceSetting = \App\Models\Setting::where('key', 'geofence')->first();
        $geofence = $geofenceSetting ? $geofenceSetting->value : null;

        if (!$geofence || !isset($geofence['latitude']) || !isset($geofence['longitude']) || $geofence['latitude'] === '' || $geofence['longitude'] === '') {
            return response()->json(['message' => 'Harap hubungi admin terlebih dahulu. Titik lokasi absensi belum diatur.'], 422);
        }

        $distance = $this->calculateDistanceMeters(
            $request->latitude,
            $request->longitude,
            $geofence['latitude'],
            $geofence['longitude']
        );

        if ($distance > ($geofence['geofence_radius_meters'] ?? 50)) {
            return response()->json(['message' => 'Di luar jangkauan area absensi. Silakan mendekat ke lokasi kantor.'], 422);
        }

        // --- CASCADING SHIFT VALIDATION ---
        $uncompletedPreviousShift = AttendanceLog::where('employee_id', $employee->id)
            ->whereBetween('check_in_at', [$dayStartUtc, $dayEndUtc])
            ->whereNull('check_out_at')
            ->first();

        if ($uncompletedPreviousShift) {
            return response()->json([
                'message' => 'Silakan Check Out pada shift sebelumnya terlebih dahulu.'
            ], 422);
        }
        // ----------------------------------

        // Shift Identification
        $shiftAssignmentId = $request->shift_assignment_id;
        $shiftTemplateId = $request->shift_template_id;
        $shiftTemplate = null;

        if ($shiftAssignmentId) {
            $assignment = \App\Models\ShiftAssignment::whereKey($shiftAssignmentId)
                ->where('employee_id', $employee->id)
                ->whereDate('date', $businessNow->toDateString())
                ->first();
            if (!$assignment) {
                return response()->json(['message' => 'Shift tidak terdaftar untuk karyawan ini.'], 422);
            }
            $shiftTemplate = $assignment->shiftTemplate;
        } else if ($shiftTemplateId) {
            $hasAssignedShift = \App\Models\ShiftAssignment::where('employee_id', $employee->id)
                ->whereDate('date', $businessNow->toDateString())->exists();
            $shiftTemplate = $hasAssignedShift ? null : \App\Models\ShiftTemplate::whereKey($shiftTemplateId)
                ->where('is_default', true)->first();
        }

        if (!$shiftTemplate) {
             $shiftTemplate = \App\Models\ShiftTemplate::where('is_default', true)->first();
        }

        if ($shiftTemplate) {
            $flags['shift_name'] = $shiftTemplate->name;
            $startTime = $shiftClock->scheduledStart(
                $shiftTemplate->start_time->format('H:i'),
                $businessNow,
            );
            $gracePeriod = $shiftTemplate->grace_period_minutes ?? 0;

            $lateThreshold = $startTime->copy()->addMinutes($gracePeriod);

            if ($businessNow->greaterThan($lateThreshold)) {
                $status = 'late';
            } elseif ($businessNow->greaterThan($startTime)) {
                $status = 'present'; // Dalam toleransi
            } else {
                $status = 'on_time'; // Tepat waktu
            }
        } else {
            $flags['shift_name'] = 'Shift Regular';
        }

        if (isset($flags['is_mock_location']) && $flags['is_mock_location'] == true) {
            $status = 'flagged';
        }

        $faceMatchScore = (float) $request->face_match_score;
        if ($request->filled('face_descriptor')) {
            $biometric = EmployeeBiometric::where('employee_id', $employee->id)->first();
            abort_unless($biometric?->web_face_embedding, 422, 'Data wajah web belum didaftarkan.');
            $faceMatchScore = app(FaceDescriptorService::class)->verifyWebDescriptor(
                $request->input('face_descriptor'),
                $biometric->web_face_embedding
            );
        } else {
            $mobileBiometric = EmployeeBiometric::where('employee_id', $employee->id)->first();
            abort_unless($mobileBiometric?->face_embedding, 422, 'Data wajah mobile belum didaftarkan atau telah direset admin. Silakan rekam ulang wajah.');
        }
        if (!$request->filled('face_descriptor') && $faceMatchScore < 0.8) {
            return response()->json([
                'message' => 'Gagal verifikasi wajah. Tingkat kemiripan di bawah 80%. Silakan coba lagi dengan pencahayaan yang baik.'
            ], 422);
        }

        $existingLogQuery = AttendanceLog::where('employee_id', $employee->id)
            ->whereBetween('check_in_at', [$dayStartUtc, $dayEndUtc]);

        if ($shiftAssignmentId) {
            $existingLogQuery->where('shift_assignment_id', $shiftAssignmentId);
        } else {
            $existingLogQuery->whereNull('shift_assignment_id');
        }

        if ($existingLogQuery->exists()) {
            return response()->json(['message' => 'Sudah melakukan check in untuk shift ini hari ini.'], 422);
        }

        $device = \App\Models\Device::where('device_fingerprint', $request->device_id)
            ->where('employee_id', $employee->id)
            ->first();

        $photoPath = null;
        if ($request->hasFile('photo')) {
            $photoPath = $request->file('photo')->store('attendance', 'public');
        }

        $attendance = AttendanceLog::create([
            'employee_id' => $employee->id,
            'shift_assignment_id' => $shiftAssignmentId,
            'check_in_at' => now(),
            'check_in_latitude' => $request->latitude,
            'check_in_longitude' => $request->longitude,
            'check_in_address' => $request->address,
            'check_in_face_score' => $faceMatchScore,
            'device_id' => $device ? $device->id : null,
            'check_in_photo_url' => $photoPath,
            'flags' => $flags,
            'status' => $status,
        ]);

        if ($status === 'flagged') {
            app(\App\Services\NotificationService::class)->sendToAdmin(
                1, 
                'Suspicious Check-in Flagged',
                "{$employee->full_name} had a suspicious check-in."
            );
        }

        return response()->json(['message' => 'Check-in successful', 'data' => $attendance]);
    }

    /**
     * Check-out an employee.
     */
    public function checkOut(Request $request)
    {
        $user = $request->user();
        $employee = $user->employee;
        $shiftClock = app(ShiftTimeService::class);
        $businessNow = $shiftClock->now();
        [$dayStartUtc, $dayEndUtc] = $shiftClock->utcDayBounds($businessNow);

        $flags = $request->flags;
        if (is_string($flags)) {
            $flags = json_decode($flags, true);
            $request->merge(['flags' => $flags]);
        }

        $validator = Validator::make($request->all(), [
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
            'face_match_score' => 'required|numeric',
            'face_descriptor' => 'nullable|array|size:128',
            'face_descriptor.*' => 'numeric|between:-10,10',
            'device_id' => 'required|string',
            'address' => 'nullable|string',
            'flags' => 'nullable|array',
            'photo' => 'nullable|image|max:10240',
            'shift_assignment_id' => 'nullable|integer',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $faceMatchScore = (float) $request->face_match_score;
        if ($request->filled('face_descriptor')) {
            $biometric = EmployeeBiometric::where('employee_id', $employee->id)->first();
            abort_unless($biometric?->web_face_embedding, 422, 'Data wajah web belum didaftarkan.');
            $faceMatchScore = app(FaceDescriptorService::class)->verifyWebDescriptor(
                $request->input('face_descriptor'),
                $biometric->web_face_embedding
            );
        } else {
            $mobileBiometric = EmployeeBiometric::where('employee_id', $employee->id)->first();
            abort_unless($mobileBiometric?->face_embedding, 422, 'Data wajah mobile belum didaftarkan atau telah direset admin. Silakan rekam ulang wajah.');
        }
        if (!$request->filled('face_descriptor') && $faceMatchScore < 0.8) {
            return response()->json([
                'message' => 'Gagal verifikasi wajah. Tingkat kemiripan di bawah 80%. Silakan coba lagi.'
            ], 422);
        }

        $shiftAssignmentId = $request->shift_assignment_id;

        // A night shift can check out on the following calendar day. Search from
        // the start of the previous business day so its check-in remains visible.
        [$previousDayStartUtc] = $shiftClock->utcDayBounds($businessNow->copy()->subDay());

        $query = AttendanceLog::where('employee_id', $employee->id)
            ->whereBetween('check_in_at', [$previousDayStartUtc, $dayEndUtc]);

        if ($shiftAssignmentId) {
            $query->where('shift_assignment_id', $shiftAssignmentId);
        } else {
            $query->whereNull('shift_assignment_id');
        }

        $attendance = $query->latest('check_in_at')->first();

        if (!$attendance) {
            return response()->json(['message' => 'Data check-in tidak ditemukan untuk shift ini.'], 404);
        }

        if ($attendance->check_out_at) {
            return response()->json(['message' => 'Sudah melakukan check out untuk shift ini.'], 422);
        }

        $geofenceSetting = \App\Models\Setting::where('key', 'geofence')->first();
        $geofence = $geofenceSetting ? $geofenceSetting->value : null;

        if (!$geofence || !isset($geofence['latitude']) || !isset($geofence['longitude']) || $geofence['latitude'] === '' || $geofence['longitude'] === '') {
            return response()->json(['message' => 'Harap hubungi admin terlebih dahulu. Titik lokasi absensi belum diatur.'], 422);
        }
        $distance = $this->calculateDistanceMeters(
            $request->latitude,
            $request->longitude,
            $geofence['latitude'],
            $geofence['longitude']
        );
        if ($distance > ($geofence['geofence_radius_meters'] ?? 50)) {
            return response()->json(['message' => 'Di luar jangkauan area absensi. Silakan mendekat ke lokasi kantor.'], 422);
        }

        $shiftTemplate = null;
        $assignment = null;
        if ($shiftAssignmentId) {
            $assignment = \App\Models\ShiftAssignment::whereKey($shiftAssignmentId)
                ->where('employee_id', $employee->id)
                ->first();
            if ($assignment) {
                $shiftTemplate = $assignment->shiftTemplate;
            }
        } else {
            $shiftTemplate = \App\Models\ShiftTemplate::where('is_default', true)->first();
        }

        if ($shiftTemplate && $shiftTemplate->end_time) {
            $workDate = $assignment?->date
                ?? $attendance->check_in_at->copy()->setTimezone(config('app.business_timezone'));
            $endTime = $shiftClock->scheduledEnd(
                $shiftTemplate->start_time->format('H:i'),
                $shiftTemplate->end_time->format('H:i'),
                $workDate,
            );
            if ($businessNow->lessThan($endTime)) {
                return response()->json(['message' => 'Belum waktunya pulang. Jam pulang Anda adalah ' . $endTime->format('H:i')], 422);
            }
        }

        $photoPath = null;
        if ($request->hasFile('photo')) {
            $photoPath = $request->file('photo')->store('attendance', 'public');
        }

        $existingFlags = $attendance->flags ?? [];
        $newFlags = $request->flags ?? [];
        $mergedFlags = array_merge($existingFlags, ['checkout_flags' => $newFlags]);

        $attendance->update([
            'check_out_at' => now(),
            'check_out_latitude' => $request->latitude,
            'check_out_longitude' => $request->longitude,
            'check_out_address' => $request->address,
            'check_out_face_score' => $faceMatchScore,
            'check_out_photo_url' => $photoPath,
            'flags' => $mergedFlags,
        ]);

        return response()->json(['message' => 'Check-out successful', 'data' => $attendance]);
    }

    public function history(Request $request)
    {
        $user = $request->user();
        
        $month = $request->query('month');
        $year = $request->query('year');
        
        $query = AttendanceLog::where('employee_id', $user->employee->id);
        
        if ($month && $year) {
            $query->whereMonth('check_in_at', $month)
                  ->whereYear('check_in_at', $year);
        }
        
        $history = $query->orderBy('check_in_at', 'desc')->paginate(31);
        
        $history->getCollection()->transform(function ($log) {
            if ($log->check_in_photo_url) {
                $log->check_in_photo_url = asset('storage/' . $log->check_in_photo_url);
            }
            if ($log->check_out_photo_url) {
                $log->check_out_photo_url = asset('storage/' . $log->check_out_photo_url);
            }
            return $log;
        });
            
        return response()->json($history);
    }

    /**
     * Get attendance info for today (Shift, Role, Tasks)
     */
    public function todayInfo(Request $request)
    {
        $employee = $request->user()->employee;
        if (!$employee) {
            return response()->json(['message' => 'Employee profile not found.'], 403);
        }
        $shiftClock = app(ShiftTimeService::class);
        $businessNow = $shiftClock->now();
        [$dayStartUtc, $dayEndUtc] = $shiftClock->utcDayBounds($businessNow);

        $shiftAssignments = \App\Models\ShiftAssignment::where('employee_id', $employee->id)
            ->whereDate('date', $businessNow->toDateString())
            ->with('shiftTemplate')
            ->get();

        $shifts = [];
        foreach ($shiftAssignments as $assignment) {
            $template = $assignment->shiftTemplate;
            if ($template) {
                $shifts[] = [
                    'assignment_id' => $assignment->id,
                    'template_id' => $template->id,
                    'name' => $template->name,
                    'category' => $template->category,
                    'start_time' => Carbon::parse($template->start_time)->format('H:i'),
                    'end_time' => Carbon::parse($template->end_time)->format('H:i'),
                ];
            }
        }

        if ($shiftAssignments->isEmpty()) {
            $defaultTemplate = \App\Models\ShiftTemplate::where('is_default', true)->first();
            if ($defaultTemplate) {
                array_unshift($shifts, [
                    'assignment_id' => null,
                    'template_id' => $defaultTemplate->id,
                    'name' => $defaultTemplate->name,
                    'category' => $defaultTemplate->category ?? 'Reguler',
                    'start_time' => Carbon::parse($defaultTemplate->start_time)->format('H:i'),
                    'end_time' => Carbon::parse($defaultTemplate->end_time)->format('H:i'),
                ]);
            }
        }

        usort($shifts, function($a, $b) {
            return strcmp($a['start_time'], $b['start_time']);
        });

        $role = [
            'employment_status' => $employee->employment_status,
            'position' => $employee->position ?? 'Karyawan',
            'department' => $employee->department ?? 'Belum ditentukan',
            'employee_name' => $employee->full_name,
        ];

        $attendances = \App\Models\AttendanceLog::where('employee_id', $employee->id)
            ->whereBetween('check_in_at', [$dayStartUtc, $dayEndUtc])
            ->get();

        foreach ($shifts as &$shift) {
            $startAt = $shiftClock->scheduledStart($shift['start_time'], $businessNow);
            $endAt = $shiftClock->scheduledEnd($shift['start_time'], $shift['end_time'], $businessNow);
            $shift['time_status'] = $businessNow->lt($startAt) ? 'upcoming' : ($businessNow->lte($endAt) ? 'active' : 'ended');
            $shift['time_status_label'] = $shift['time_status'] === 'upcoming'
                ? 'Belum dimulai'
                : ($shift['time_status'] === 'active' ? 'Sedang berlangsung' : 'Jadwal selesai');
            $log = $attendances->first(function($att) use ($shift) {
                return $att->shift_assignment_id == $shift['assignment_id'];
            });

            if ($log) {
                $shift['attendance'] = [
                    'id' => $log->id,
                    'check_in_time' => $log->check_in_at,
                    'check_out_time' => $log->check_out_at,
                    'check_in_address' => $log->check_in_address,
                    'check_out_address' => $log->check_out_address,
                    'status' => $log->status,
                ];
            } else {
                $shift['attendance'] = null;
            }
        }

        // --- Calculate Monthly Stats ---
        $currentMonth = $businessNow->month;
        $currentYear = $businessNow->year;

        $monthlyLogs = \App\Models\AttendanceLog::where('employee_id', $employee->id)
            ->whereMonth('check_in_at', $currentMonth)
            ->whereYear('check_in_at', $currentYear)
            ->get();

        $onTimeCount = $monthlyLogs->where('status', 'on_time')->count();
        $gracePeriodCount = $monthlyLogs->where('status', 'present')->count();
        $lateCount = $monthlyLogs->where('status', 'late')->count();
        $totalPresentCount = $onTimeCount + $gracePeriodCount + $lateCount;

        // Determine passed working days
        $workingDaysSetting = \App\Models\Setting::where('key', 'working_days')->first();
        $workingDays = $workingDaysSetting ? $workingDaysSetting->value : [1, 2, 3, 4, 5, 6];
        if (is_string($workingDays)) {
            $workingDays = json_decode($workingDays, true);
        }

        $passedWorkingDays = 0;
        $startOfMonth = $businessNow->copy()->startOfMonth();
        $today = $businessNow->copy()->startOfDay();

        for ($date = $startOfMonth; $date->lte($today); $date->addDay()) {
            // isDayOfWeek requires ISO day of week (1 = Monday, 7 = Sunday)
            // Carbon's dayOfWeek returns 0 (Sunday) to 6 (Saturday).
            // Let's use isoFormat('E') which returns 1-7
            $dayOfWeek = (int) $date->isoFormat('E');
            if (in_array($dayOfWeek, $workingDays)) {
                $passedWorkingDays++;
            }
        }

        $absentCount = max(0, $passedWorkingDays - $totalPresentCount);
        $percentage = $passedWorkingDays > 0 ? round(($totalPresentCount / $passedWorkingDays) * 100, 1) : 100;
        if ($percentage > 100) $percentage = 100;

        $monthlyStats = [
            'on_time' => $onTimeCount,
            'grace_period' => $gracePeriodCount,
            'late' => $lateCount,
            'absent' => $absentCount,
            'percentage' => $percentage
        ];
        // -------------------------------

        return response()->json([
            'shifts' => $shifts,
            'role' => $role,
            'monthly_stats' => $monthlyStats,
        ]);
    }
}
